# Generated by Django 6.0.1 on 2026-02-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Why user was rejected')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobApplication.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('recommended_level', models.CharField(choices=[('Beginner', 'Beginner'), ('intermediate', 'intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('resources', models.TextField(blank=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='roadmap.roadmap')),
            ],
        ),
    ]
