# Generated by Django 6.0.1 on 2026-02-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApplication', '0002_alter_jobapplication_unique_together'),
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='jobApplication.jobapplication'),
        ),
    ]
