# Generated by Django 6.0.1 on 2026-02-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skill_level_alter_skill_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='status',
        ),
    ]
