# Generated by Django 4.2.10 on 2026-02-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_remove_skill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
