# Generated by Django 6.0.1 on 2026-02-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApplication', '0002_alter_jobapplication_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rejection_type',
            field=models.CharField(blank=True, choices=[('Skill_Gap', 'Skill Gap'), ('CULTURE_FIT', 'Culture Fit'), ('COMMUNICATION', 'Communication'), ('EXPERIENCE', 'Experience Level'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
    ]
