# Generated by Django 6.0.1 on 2026-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApplication', '0003_jobapplication_rejection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='rejection_type',
            field=models.CharField(blank=True, choices=[('SKILL_GAP', 'Skill Gap'), ('CULTURE_FIT', 'Culture Fit'), ('COMMUNICATION', 'Communication'), ('EXPERIENCE', 'Experience Level'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
    ]
